In [1]:
import numpy as np
array_A = np.array([[2,4,6], [1,3,5]])


In [2]:
import numpy as np
a = np.array([20,30,40,50,60])
b = np.array([4,5,6,7,8])
np.add(a, b)

array([24, 35, 46, 57, 68])

In [3]:
import numpy as np
a = np.array([20,30,40,50,60])
b = np.array([4,5,6,7,8])
c = a+b
print(c)
print(type(c))


[24 35 46 57 68]
<class 'numpy.ndarray'>


In [4]:
print('The max is' ,array_A.max(axis=0))
print('The min is' ,array_A.min())

The max is [2 4 6]
The min is 1


In [5]:
import numpy as np
a = np.array([20,3,40,50,60])
b = np.array([4,5,6,7,8])
c = a-b
print(c)


[16 -2 34 43 52]


In [6]:
array_A.ravel()


array([2, 4, 6, 1, 3, 5])

In [7]:
import numpy as np
a = np.array([20,30,40,50,60])
b = np.array([4,5,6,7,8])
print(np.multiply(b, a))
print(a*b)

[ 80 150 240 350 480]
[ 80 150 240 350 480]


In [8]:
import numpy as np
a = np.array([20,30,40,50,60])
b = np.array([4,5,6,7,8])
print(np.divide(a, b))
print(a/b)

[5.         6.         6.66666667 7.14285714 7.5       ]
[5.         6.         6.66666667 7.14285714 7.5       ]


In [9]:
import numpy as np
a = np.array([2,3,4,5,6])
b = np.array([5,4,3,2,1])
print(np.mod(a, b))
print(np.remainder(a,b))


[2 3 1 1 0]
[2 3 1 1 0]


In [10]:
array_x = np.array([5,6,7,8,9])
print('The max is' ,array_x.max())
print('The min is' ,array_x.min())

The max is 9
The min is 5


In [11]:
import numpy as np
a = np.array([2.5,3.5 ,4.3,5.4,6.5])
print(np.reciprocal(a))

[0.4        0.28571429 0.23255814 0.18518519 0.15384615]


In [12]:
import numpy as np
a = np.array([2.5,3.5 ,4.3,5.4,6.5])
print('The sum is ', np.sum(a))
print('The mean is ', np.mean(a))
print('The average is ', np.average(a))
print('The variance is ', np.var(a))


The sum is  22.200000000000003
The mean is  4.44
The average is  4.44
The variance is  1.9664000000000001


In [13]:
arr1 = np.linspace(1,10,5)
arr1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
array_x

array([5, 6, 7, 8, 9])

In [15]:
array_x[0]

5

In [16]:
array_x[:3]

array([5, 6, 7])

In [17]:
array_x[3:]

array([8, 9])

In [18]:
array_x[0:-1:2]

array([5, 7])

In [19]:
array_A

array([[2, 4, 6],
       [1, 3, 5]])

In [20]:

array_A[0,0]


2

In [21]:
array_A[1, 1]

3

In [22]:
array1 = np.append(array_x, 1)
array1

array([5, 6, 7, 8, 9, 1])

In [23]:
array2= np.delete(array1,2)
array2

array([5, 6, 8, 9, 1])

In [24]:
array3 = np.sort(array2)
array3

array([1, 5, 6, 8, 9])

In [25]:
arr2 = np.reshape(array_A,(3,2))
arr2

array([[2, 4],
       [6, 1],
       [3, 5]])

In [26]:
arr_ful = np.full(shape=(5,6), fill_value=3)
arr_ful

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [27]:
arr2.flatten()

array([2, 4, 6, 1, 3, 5])